# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: customer_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ustomer_service.proto\x12\x08\x63ustomer\"^\n\x0fIdentifyRequest\x12\x13\n\x0bplatform_id\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x02 \x01(\t\x12\x10\n\x08platform\x18\x03 \x01(\t\x12\x0e\n\x06\x61pp_id\x18\x04 \x01(\t\"J\n\x10\x43ustomerResponse\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\t\x12\x0e\n\x06is_new\x18\x02 \x01(\x08\x12\x11\n\tfull_name\x18\x03 \x01(\t2\\\n\x0f\x43ustomerService\x12I\n\x10IdentifyCustomer\x12\x19.customer.IdentifyRequest\x1a\x1a.customer.CustomerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'customer_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IDENTIFYREQUEST']._serialized_start=36
  _globals['_IDENTIFYREQUEST']._serialized_end=130
  _globals['_CUSTOMERRESPONSE']._serialized_start=132
  _globals['_CUSTOMERRESPONSE']._serialized_end=206
  _globals['_CUSTOMERSERVICE']._serialized_start=208
  _globals['_CUSTOMERSERVICE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
