# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import customer_service_pb2 as customer__service__pb2


class CustomerServiceStub(object):
    """This service is used for identifying customers based on their platform details.
    It provides the RPC method 'IdentifyCustomer' to retrieve the customer ID and other details.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IdentifyCustomer = channel.unary_unary(
            "/customer.CustomerService/IdentifyCustomer",
            request_serializer=customer__service__pb2.IdentifyRequest.SerializeToString,
            response_deserializer=customer__service__pb2.CustomerResponse.FromString,
        )


class CustomerServiceServicer(object):
    """This service is used for identifying customers based on their platform details.
    It provides the RPC method 'IdentifyCustomer' to retrieve the customer ID and other details.
    """

    def IdentifyCustomer(self, request, context):
        """The RPC method the Webhook Service will call"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_CustomerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "IdentifyCustomer": grpc.unary_unary_rpc_method_handler(
            servicer.IdentifyCustomer,
            request_deserializer=customer__service__pb2.IdentifyRequest.FromString,
            response_serializer=customer__service__pb2.CustomerResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "customer.CustomerService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class CustomerService(object):
    """This service is used for identifying customers based on their platform details.
    It provides the RPC method 'IdentifyCustomer' to retrieve the customer ID and other details.
    """

    @staticmethod
    def IdentifyCustomer(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/customer.CustomerService/IdentifyCustomer",
            customer__service__pb2.IdentifyRequest.SerializeToString,
            customer__service__pb2.CustomerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
